"""Контракты данных: модели, которыми обмениваются сервисы конвейера.

Публичный API пакета — реэкспорт из всех подмодулей (`raw`, `canonical`,
`enriched`, `ranges`, `analysis`, `explanation`, `vision`), чтобы последующие задачи
импортировали из `harness.contracts`, а не из отдельных модулей.
"""

from __future__ import annotations

from harness.contracts.analysis import (
    UNJUDGED_DECISION_NOT_TAKEN,
    AllInEvent,
    AnalysisResult,
    Assumption,
    ChipMove,
    EvInterval,
    EvSplit,
    Finding,
    LevelLine,
    PlayerStats,
    PointVerdict,
    ScanItem,
    ScanSummary,
    SpotKind,
    StackTrajectory,
    TournamentReport,
    Zone,
)
from harness.contracts.canonical import (
    CanonicalAction,
    CanonicalHand,
    Identity,
    PlayerState,
)
from harness.contracts.enriched import (
    DecisionPoint,
    EngineReport,
    EnrichedHand,
    SidePot,
    ValidationStatus,
    Verdict,
)
from harness.contracts.explanation import (
    PointText,
    TournamentTextOut,
    VerdictLabel,
    VerdictTextOut,
)
from harness.contracts.history import (
    JUDGED_SPOTS,
    LEAK_RULES,
    MAX_NOTE_TEXT_CHARS,
    NOTE_COLOR_NONE,
    NOTE_COLORS,
    LeakRule,
    LeaksOverview,
    LeakStat,
    NoteColor,
    NoteRecord,
    OpponentRecord,
    SessionLine,
    SessionSummary,
    leak_rule_for,
    leak_rule_of_point,
)
from harness.contracts.ranges import RANKS, Range, all_classes, class_of
from harness.contracts.raw import (
    ActionKind,
    Collected,
    Completeness,
    Post,
    PostKind,
    Provenance,
    RawAction,
    RawHand,
    SeatInfo,
    ShowdownEntry,
    Street,
    SummaryInfo,
    Uncalled,
    VisionCheck,
    VisionHop,
    VisionMeta,
)
from harness.contracts.vision import (
    SeenAction,
    SeenPlayer,
    SeenPost,
    SeenWin,
    Unit,
    VisionReading,
)

__all__ = [
    "JUDGED_SPOTS",
    "LEAK_RULES",
    "MAX_NOTE_TEXT_CHARS",
    "NOTE_COLORS",
    "NOTE_COLOR_NONE",
    "RANKS",
    "UNJUDGED_DECISION_NOT_TAKEN",
    "ActionKind",
    "AllInEvent",
    "AnalysisResult",
    "Assumption",
    "CanonicalAction",
    "CanonicalHand",
    "ChipMove",
    "Collected",
    "Completeness",
    "DecisionPoint",
    "EngineReport",
    "EnrichedHand",
    "EvInterval",
    "EvSplit",
    "Finding",
    "Identity",
    "LeakRule",
    "LeakStat",
    "LeaksOverview",
    "LevelLine",
    "NoteColor",
    "NoteRecord",
    "OpponentRecord",
    "PlayerState",
    "PlayerStats",
    "PointText",
    "PointVerdict",
    "Post",
    "PostKind",
    "Provenance",
    "Range",
    "RawAction",
    "RawHand",
    "ScanItem",
    "ScanSummary",
    "SeatInfo",
    "SeenAction",
    "SeenPlayer",
    "SeenPost",
    "SeenWin",
    "SessionLine",
    "SessionSummary",
    "ShowdownEntry",
    "SidePot",
    "SpotKind",
    "StackTrajectory",
    "Street",
    "SummaryInfo",
    "TournamentReport",
    "TournamentTextOut",
    "Uncalled",
    "Unit",
    "ValidationStatus",
    "Verdict",
    "VerdictLabel",
    "VerdictTextOut",
    "VisionCheck",
    "VisionHop",
    "VisionMeta",
    "VisionReading",
    "Zone",
    "all_classes",
    "class_of",
    "leak_rule_for",
    "leak_rule_of_point",
]
