"""initial

Схема v1: 12 таблиц спеки §6 (docs/superpowers/specs/2026-08-28-poker-harness-tech-spec-design.md).
Сгенерировано `alembic revision --autogenerate` из `harness.memory.models.Base.metadata` и
проверено вручную по строкам таблицы §6 (задача 14) — расхождений с моделями нет, правка не
потребовалась.

Revision ID: 0001
Revises:
Create Date: 2026-09-04 01:01:49.397577

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calc_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_calc_cache'))
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('quota_daily', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.String(length=32), server_default='free', nullable=False),
    sa.Column('is_dev', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_players_tg_user_id'))
    )
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['players.id'], name=op.f('fk_invites_issued_by_players')),
    sa.ForeignKeyConstraint(['used_by'], ['players.id'], name=op.f('fk_invites_used_by_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_invites_code'))
    )
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_player_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_nick', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_player_id'], ['players.id'], name=op.f('fk_notes_owner_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_sessions_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('tournaments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('scan_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_tournaments_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_table('hands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("provenance IN ('hand_history', 'screenshot')", name=op.f('ck_hands_provenance_allowed')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_hands_session_id_sessions')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_hands_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hands'))
    )
    op.create_index('ix_hands_session_id', 'hands', ['session_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict_text', sa.Text(), nullable=True),
    sa.Column('range_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_analyses_hand_id_hands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_table('eval_cases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('vision_field', 'verdict_confirm', 'verdict_dispute')", name=op.f('ck_eval_cases_kind_allowed')),
    sa.CheckConstraint("source IN ('escalation', 'disagree_button', 'manual')", name=op.f('ck_eval_cases_source_allowed')),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_eval_cases_hand_id_hands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_cases'))
    )
    op.create_index('ix_eval_cases_kind', 'eval_cases', ['kind'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('hand_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'awaiting_user', 'done', 'failed')", name=op.f('ck_jobs_status_allowed')),
    sa.CheckConstraint("type IN ('screenshot_analyze', 'hh_scan', 'deep_dive', 'eval_run')", name=op.f('ck_jobs_type_allowed')),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_jobs_hand_id_hands')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_jobs_player_id_players')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_jobs_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_player_id_status', 'jobs', ['player_id', 'status'], unique=False)
    op.create_index('ix_jobs_status_priority_created_at', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('hand_id', sa.BigInteger(), nullable=True),
    sa.Column('spans', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_traces_hand_id_hands')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_traces_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traces'))
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='started', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('vision_extract', 'verdict_text')", name=op.f('ck_llm_calls_purpose_allowed')),
    sa.CheckConstraint("status IN ('started', 'ok', 'error', 'schema_error')", name=op.f('ck_llm_calls_status_allowed')),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], name=op.f('fk_llm_calls_trace_id_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_started_at', 'llm_calls', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_started_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('traces')
    op.drop_index('ix_jobs_status_priority_created_at', table_name='jobs')
    op.drop_index('ix_jobs_player_id_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_eval_cases_kind', table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_table('analyses')
    op.drop_index('ix_hands_session_id', table_name='hands')
    op.drop_table('hands')
    op.drop_table('tournaments')
    op.drop_table('sessions')
    op.drop_table('notes')
    op.drop_table('invites')
    op.drop_table('players')
    op.drop_table('calc_cache')
    # ### end Alembic commands ###
