"""jobs: партиционный уникальный индекс running-задач на игрока

Задача 15, fix round 1 (ревью нашло Critical): `NOT EXISTS` в SQL захвата
(`platform/queue.py`, `_CLAIM_SQL`) под READ COMMITTED видит только
закоммиченное, и `FOR UPDATE SKIP LOCKED` блокирует только строку-кандидата, а
не строки, которые смотрит `NOT EXISTS` — два конкурентных `claim()` могли
одновременно забрать РАЗНЫЕ `queued`-задачи одного игрока (воспроизведено
300/300 на реальном Postgres 16). Индекс — структурная гарантия «одна активная
задача на игрока» (спека §8.1) поверх этого SQL-фильтра, а не вместо него:
`NOT EXISTS` остаётся быстрым путём без лишних блокировок в общем случае,
индекс — гарантия на случай, когда быстрый путь ошибся.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-04 01:45:48.264431

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_jobs_player_id_running', 'jobs', ['player_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_jobs_player_id_running', table_name='jobs', postgresql_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###
