"""псевдонимы: оппонент по нику и его метки в турнирах

Сшивание личности между турнирами. В файлах раздач участник обезличен, и его
идентификатор сквозной только внутри турнира — между турнирами комната выдаёт
новый. Связь утверждает владелец: «этот участник — такой-то ник», а система не
угадывает её ни по чему.

1. `player_aliases` — оппонент владельца, известный по нику в руме. Ник, а не
   произвольный ярлык (решение владельца): ярлык описывает место за столом, а
   не человека. Уникальность — функциональный индекс
   `(owner_player_id, lower(opponent_nick))`: регистр не различается, написание
   хранится то, которым ник ввели в первый раз. Длина колонки — та же, что у
   `players.gg_nickname`.

2. `player_alias_links` — пара «турнир + идентификатор участника» → ник.
   Турнир записан так, как его нумерует комната (`CanonicalHand.tournament_id`),
   а не строкой таблицы `tournaments`: один турнир бывает загружен дважды, и
   привязка не имеет права от этого раздваиваться; внешнего ключа на
   `tournaments` поэтому нет вовсе. Первичный ключ
   `(owner_player_id, room_tournament_id, participant_label)` и есть требуемая
   уникальность «один идентификатор в одном турнире у одного владельца привязан
   не более чем к одному псевдониму» — правило держит база, а не проверка в
   коде. Владелец в ключе — денормализация (индекс не умеет джойнить), и чтобы
   она не разошлась с владельцем самого псевдонима, ссылка составная:
   `(alias_id, owner_player_id)` на `player_aliases(id, owner_player_id)`,
   `ON DELETE CASCADE`.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-08 21:59:19.297401

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_aliases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_player_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_nick', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['owner_player_id'], ['players.id'], name=op.f('fk_player_aliases_owner_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_aliases')),
    sa.UniqueConstraint('id', 'owner_player_id', name='uq_player_aliases_id_owner')
    )
    op.create_index('uq_player_aliases_owner_player_id_lower_nick', 'player_aliases', ['owner_player_id', sa.literal_column('lower(opponent_nick)')], unique=True)
    op.create_table('player_alias_links',
    sa.Column('owner_player_id', sa.BigInteger(), nullable=False),
    sa.Column('room_tournament_id', sa.String(), nullable=False),
    sa.Column('participant_label', sa.String(), nullable=False),
    sa.Column('alias_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alias_id', 'owner_player_id'], ['player_aliases.id', 'player_aliases.owner_player_id'], name='fk_player_alias_links_alias_player_aliases', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_player_id', 'room_tournament_id', 'participant_label', name='pk_player_alias_links'),
    sa.UniqueConstraint('alias_id', 'room_tournament_id', name='uq_player_alias_links_alias_tournament')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_alias_links')
    op.drop_index('uq_player_aliases_owner_player_id_lower_nick', table_name='player_aliases')
    op.drop_table('player_aliases')
    # ### end Alembic commands ###
